apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: example-org-tls
spec:
  host: example.org
  trafficPolicy:
    tls:
      mode: SIMPLE
      caCertificates: /etc/ssl/certs/ca-certificates.crt

